namespace MicroXYZ.Enums
{
    public enum EMailSMTPTemplatesEnum
    {
        CONTACT_US_FORM_TEMPLATE,
        PRODUCT_BUY_REQUEST_TEMPLATE,
        PRODUCT_BUY_CUSTOMER_TEMPLATE,
        E_MAIL_VERIFY_TEMPLATE,
        SUBSCRIBE_TEMPLATE,
        FORGET_PASSWORD_TEMPLATE,
    }
}
