namespace MicroXYZ.Enums
{
    public enum EMailSMTPSettingsEnum
    {
        SMTP_EPOSTA_ADDRESS,
        SMTP_EPOSTA_PASSWORD,
        SMTP_EPOSTA_HTML_TEMPLATE,
        SMTP_EPOSTA_HOST,
        SMTP_EPOSTA_PORT,
        SMTP_EPOSTA_SSL,
        SMTP_EPOSTA_CONTACT_US_HTML_TEMPLATE,
        SMTP_EPOSTA_FORGET_PASSWORD_HTML_TEMPLATE
    }
}
